backend:
  name: git-gateway
  branch: main

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "events"
    label: "Events"
    folder: "_events"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    editor:
      preview: false
    fields:
      - {label: "Event Title", name: "title", widget: "string", hint: "Name of the event"}
      - {label: "Event Image", name: "image", widget: "image", hint: "Upload a picture for this event"}
      - {label: "Event Date", name: "date", widget: "datetime", hint: "When is this event happening?"}
      - {label: "Event Time", name: "time", widget: "string", hint: "e.g. 7:00 PM - 11:00 PM"}
      - {label: "Description", name: "description", widget: "text", hint: "Brief description of the event"}
      - {label: "Event Details", name: "body", widget: "markdown", required: false, hint: "Full event details (optional)"}
      - {label: "Location", name: "location", widget: "select", options: ["Large Hall", "Small Hall", "Both Halls", "Outdoor Area"], default: "Large Hall"}
      - {label: "Ticket Price", name: "price", widget: "string", required: false, hint: "e.g. Free, €10, €15-25"}
      - {label: "Status", name: "status", widget: "select", options: ["upcoming", "sold-out", "cancelled"], default: "upcoming"}

